using ReportManager.Models;

namespace ReportManager.DataAccess.Repository;
public interface IParametersMoldingAndInitialExposureProcessRepository : IRepository<Parameters_molding_and_initial_exposure_process> { }