using KafkaConsumer.Models;

namespace KafkaConsumer.DataAccess.Repository;
public interface IParametersMoldingAndInitialExposureProcessRepository : IRepository<Parameters_molding_and_initial_exposure_process> { }